// <auto-generated />
using System;
using Axios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Axios.Migrations
{
    [DbContext(typeof(AxiosContext))]
    partial class AxiosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Axios.Models.Alarma", b =>
                {
                    b.Property<int>("Id_Alarma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Alarma"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Alarma");

                    b.ToTable("Alarmas");

                    b.HasData(
                        new
                        {
                            Id_Alarma = 1,
                            Nombre = "",
                            Ruta = ""
                        },
                        new
                        {
                            Id_Alarma = 2,
                            Nombre = "Zumbido",
                            Ruta = "xxxxx/Zumbido.mp3"
                        },
                        new
                        {
                            Id_Alarma = 3,
                            Nombre = "Pitido",
                            Ruta = "xxxxx/Pitido.mp3"
                        },
                        new
                        {
                            Id_Alarma = 4,
                            Nombre = "Himno",
                            Ruta = "xxxxx/Colombia.mp3"
                        });
                });

            modelBuilder.Entity("Axios.Models.Tarea", b =>
                {
                    b.Property<int>("Id_Tarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tarea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha_Limite")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("ID_Alarma")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Tarea");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id_Tarea = 1,
                            Descripcion = "Tengo que salir por más tardar a esta hora para llegar",
                            Fecha_Limite = new DateOnly(2025, 10, 28),
                            Hora = new TimeOnly(12, 30, 0),
                            ID_Alarma = 0,
                            ID_Usuario = 1,
                            Titulo = "Cita Odontologica"
                        },
                        new
                        {
                            Id_Tarea = 2,
                            Descripcion = "El Examen comienza a esta hora",
                            Fecha_Limite = new DateOnly(2025, 12, 5),
                            Hora = new TimeOnly(10, 0, 0),
                            ID_Alarma = 1,
                            ID_Usuario = 2,
                            Titulo = "Examen Estadistica"
                        },
                        new
                        {
                            Id_Tarea = 3,
                            Descripcion = "A esta hora tengo que tomar mis pastillas",
                            Fecha_Limite = new DateOnly(2025, 10, 15),
                            Hora = new TimeOnly(9, 30, 0),
                            ID_Alarma = 2,
                            ID_Usuario = 3,
                            Titulo = "Pastillas para presión"
                        });
                });

            modelBuilder.Entity("Axios.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            Contraseña = "DispositivosMoviles",
                            Correo = "Fernando.buelvas176@pascualbravo.edu.co",
                            Nombre = "Fernando José"
                        },
                        new
                        {
                            Id_Usuario = 2,
                            Contraseña = "DispositivosMoviles123",
                            Correo = "Juan.Calderon698@pascualbravo.edu.co",
                            Nombre = "Juan Calderon"
                        },
                        new
                        {
                            Id_Usuario = 3,
                            Contraseña = "Cardona",
                            Correo = "Omar.Cardona@pascualbravo.edu.co",
                            Nombre = "Omar Andres"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
